public class freshdeskContactWrapper{
	public boolean active;
	public String address;
	public String company_id;
	public String description;
	public String email;	//rachel@freshdesk.com
	public String id;	//2
	public String job_title;
	public String mobile;
	public String name;	//Rachel
	public String phone;
	public String twitter_id;
	public String created_at;	//2015-08-18T16:18:14Z
	public String updated_at;	//2015-08-24T09:25:19Z
		
}